name : coverage

on : 
  pull_request:
    branches :
      - main

jobs:
  coverage:
    runs-on : ubuntu-latest

    steps:
      - name : checkout code
        uses : actions/checkout@v4

      - name : setup python
        uses : actions/setup-python@v5
        with:
            python-version : "3.12"
      
      - name : install dependencies
        run : pip install -r requirements.txt

      - name : coverage
        run : |
          pytest --cov=src --cov-report=term-missing --cov-fail-under=85
